# MNIST 필기체 숫자 데이터 세트

In [17]:
import tensorflow as tf

In [18]:
mnist = tf.keras.datasets.mnist.load_data()
# print(mnist)
# print(mnist[0])
print(mnist[0][0])

data=mnist[0][0]
print(data.shape)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
(60000, 28, 28)


In [19]:
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()
X_train.shape
y_train.shape

(60000,)

In [20]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Input(shape=(28*28,)))
model.add(tf.keras.layers.Dense(units=512, activation='relu', name='Hidden1'))
model.add(tf.keras.layers.Dense(units=256, activation='relu', name='Hidden2'))
model.add(tf.keras.layers.Dense(units=10, activation='softmax', name='outputlayer')) # 10개는 결과값

In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden1 (Dense)                 │ (None, 512)            │       401,920 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden2 (Dense)                 │ (None, 256)            │       131,328 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ outputlayer (Dense)             │ (None, 10)             │         2,570 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 535,818 (2.04 MB)

 Trainable params: 535,818 (2.04 MB)

 Non-trainable params: 0 (0.00 B)

In [22]:
X_images = X_train.reshape((60000, 28*28))
type((X_images[0] / 255).dtype)

numpy.dtypes.Float64DType

In [23]:
X_images_norm = (X_images / 255).astype('float32')

In [24]:
X_images_test = X_test.reshape((10000, 28*28))
X_images_test_norm = (X_images_test / 255).astype('float32')
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X_images_norm, y_train, epochs=30) # 학습시킨다. norm을 붙인다. accuracy가 1에 가까울수록 학습이 잘되는것. 

Epoch 1/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9441 - loss: 0.1868
Epoch 2/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9754 - loss: 0.0784
Epoch 3/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9821 - loss: 0.0564
Epoch 4/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9872 - loss: 0.0399
Epoch 5/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9902 - loss: 0.0321
Epoch 6/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9905 - loss: 0.0286
Epoch 7/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9923 - loss: 0.0239
Epoch 8/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9931 - loss: 0.0215
Epoch 9/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9939 - loss: 0.0182
Epoch 10/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9951 - loss: 0.0169
Epoch 11/30
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9951 - loss: 0.0159
Epoch 12/30
1875/1875 ━━━━━━━━

In [25]:
model.save("MNIST_260626_15-30.keras") # 잘된 모델을 저장한다. (하고나서 )
model.evaluate(X_images_test_norm, y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9816 - loss: 0.1689


[0.16892285645008087, 0.9815999865531921]

In [26]:
import cv2

In [27]:
img = cv2.imread("dig.png", cv2.IMREAD_GRAYSCALE) # 흑백으로 먼저 만들어야 한다..
cv2.imshow("IMAGE", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [28]:
resize_img = cv2.resize(img, (28, 28))# 이미지 크기를 28*28로 축소시켜야 한다.
resize_img = resize_img.astype("float32")
inverse_img = 255 - resize_img # 이미지를 반전해야 한다

cv2.imshow("IMAGE", inverse_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

inverse_img_norm = inverse_img / 255.0

In [30]:
result = model.predict(inverse_img_norm.reshape(1,784))
print(result)
print(result.argmax())

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
[[6.1967503e-15 8.5024205e-23 8.6401993e-01 1.1975863e-19 2.1423879e-24
  3.5355830e-13 6.9377168e-18 4.1441617e-22 1.3598005e-01 2.6951073e-20]]
2
