# 원-핫 인코딩

In [ ]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder
import tensorflow as tf

In [2]:
X = np.array([['Korea', 44, 7200], ['Japan', 27, 4800], ['China', 30, 6100]])

onehotencoder = OneHotEncoder()
XX = onehotencoder.fit_transform(X[:,0].reshape(-1,1)).toarray()

print(XX)
X = np.delete(X, [0], axis=1) # 0번째 열 삭제
X = np.concatenate((XX, X), axis = 1) # X와 XX를 붙인다

print(X)

[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
[['0.0' '0.0' '1.0' '44' '7200']
 ['0.0' '1.0' '0.0' '27' '4800']
 ['1.0' '0.0' '0.0' '30' '6100']]


# 원-핫 인코딩 (케라스 사용)

In [ ]:
class_vector = [2, 6, 6, 1]
output = to_categorical(class_vector, num_classes = 7)
print(output)

TypeError: to_categorical() got an unexpected keyword argument 'dtype'