In [1]:
import numpy as np
import time

In [60]:
list1 = [1,2,3,4,5]
a = np.array(list1)
print(type(list1))
print(type(a))
print(list1)
print(a)

<class 'list'>
<class 'numpy.ndarray'>
[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [61]:
list_a = [10, 20, 30]
list_b = [20, 30, 40]

In [62]:
print(list_a + list_b)

[10, 20, 30, 20, 30, 40]


In [63]:
print(np.array(list_a) + np.array(list_b))

[30 50 70]


In [64]:
a.dtype

dtype('int64')

In [65]:
b = np.array([[1,2,3], [4,5,6]])
b.shape

(2, 3)

In [66]:
b = np.array([[10, 20, 30], [40, 50, 60]])
c = np.array([2, 3, 4])
b + c

array([[12, 23, 34],
       [42, 53, 64]])

In [67]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [68]:
print(np.eye(4) * 10)

[[10.  0.  0.  0.]
 [ 0. 10.  0.  0.]
 [ 0.  0. 10.  0.]
 [ 0.  0.  0. 10.]]


In [69]:
range(10)

range(0, 10)

In [70]:
list1:list = [i for i in range(10)]
print(list1)  # list1 '주소'를 가져옴
print(list1[0])  # list1 의 0번째 '값'을 가져옴

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
0


In [71]:
for i in np.arange(10):
    print(i, end = "\t")

0	1	2	3	4	5	6	7	8	9	

In [72]:
for i in np.arange(0, 5, 0.2) :
    print(i, end = "\t")

0.0	0.2	0.4	0.6000000000000001	0.8	1.0	1.2000000000000002	1.4000000000000001	1.6	1.8	2.0	2.2	2.4000000000000004	2.6	2.8000000000000003	3.0	3.2	3.4000000000000004	3.6	3.8000000000000003	4.0	4.2	4.4	4.6000000000000005	4.800000000000001	

In [73]:
0.1 + 0.2 #부동소수점 오류가 나온다. 0.30000000000000004

0.30000000000000004

In [74]:
np.arange(10)[9]

np.int64(9)

In [75]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [76]:
np.linspace(0, 5, 5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [77]:
np.logspace(0, 5, 6)

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [78]:
np.log10(np.logspace(0, 5, 6))

array([0., 1., 2., 3., 4., 5.])

In [79]:
x = np.linspace(0, np.pi, 11)
print(np.sin(x))

[0.00000000e+00 3.09016994e-01 5.87785252e-01 8.09016994e-01
 9.51056516e-01 1.00000000e+00 9.51056516e-01 8.09016994e-01
 5.87785252e-01 3.09016994e-01 1.22464680e-16]


In [12]:
a = np.array ([[1,1], [2,2], [3,3]])
np.insert(a, 1, 4, axis = 0)
print(a)

[[1 1]
 [2 2]
 [3 3]]


In [18]:
c = np.array([[1,2,3], [4,5,6]])
print(np.flip(np.flip(c, axis=0), axis=1))

[[6 5 4]
 [3 2 1]]


In [25]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9], [0,1,2]])
print(arr_2d[1:, 0:1])

[[4]
 [7]
 [0]]


In [26]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12], [13,14,15,16]])
a % 2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [33]:
x = np.arange(1,17).reshape(4,4)
print(x)
result = x % 2 ==0
print(result)
x[x % 2 ==0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]]


array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [43]:
d = np.array([[35, 24, 55], [69, 19, 9], [4, 1, 11]])
d.sort(axis=0)
print(np.flip(d, axis=0))

[[69 24 55]
 [35 19 11]
 [ 4  1  9]]


In [55]:
a = np.arange(1,10)
a = a.reshape(-1,3)
b = np.full((3,3),3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [4]:
a = np.arange(0,8)
print(a)

def train_test_split(numbers):
    np.random.shuffle(numbers)
    divisor = int(len(numbers) * 0.8)
    train = numbers[:divisor]
    test = numbers[divisor:]
    return (train, test)
x = np.arange(1, 51)
(train, test) = train_test_split(x)
print(f"train: {train}, \nTest : {test}")

[0 1 2 3 4 5 6 7]
train: [15 28 41 16  1 39 34 45 26 12  2 35 25 14 47 27 49 31  6 44 33 20 40 11
 30 24 48  8  5 19 23 38  9 21 32 50  4 37 10 36], 
Test : [29  7 43 22 42 18 17  3 46 13]


In [2]:
arr_a = np.random.rand(100)
arr_b = np.random.rand(100)

start = time.time()
c = arr_a * arr_b
end = time.time()
print("소요시간 : ", end - start)

소요시간 :  7.152557373046875e-05
